yolo_model:

  config_file:
    name: robocup2019.cfg
  weight_file:
    name: yolo-robocup2019.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - biscuit
      - frosty fruits
      - snakes
      - cloth
      - dishwasher tab
      - sponge
      - trash bags
      - beer
      - chocolate milk
      - coke
      - juice
      - lemonade
      - tea bag
      - water
      - carrot
      - cereals
      - noodles
      - onion
      - vegemite
      - apple
      - kiwi
      - lemon
      - orange
      - pear
      - cheetos
      - doritos
      - shapes chicken
      - shapes pizza
      - twisties
      - bowl
      - shot glass
